import {useEffect,useState} from 'react';
import {AdminPicker} from '../../components/AdminPicker';
import {nestRequest} from '../../services/nestClient';
import {getActiveStoreId,STORE_CONTEXT_CHANGED_EVENT} from '../../data/multiStoreStore';
type Config={settings:{provider_id:string;enabled:boolean;cache_days:number;configured:boolean}|null;providers:{id:string;name:string;docs_url:string}[];brands:{name:string}[]};
export function DeviceCatalogSettingsPage(){
 const [config,setConfig]=useState<Config>();const [provider,setProvider]=useState('');const [key,setKey]=useState('');const [enabled,setEnabled]=useState(false);const [days,setDays]=useState(30);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;let generation=0;const load=()=>{const current=++generation;setBusy(false);setConfig(undefined);setKey('');setError('');setMessage('');void nestRequest<Config>('/device-reference/settings').then(data=>{if(!alive||current!==generation)return;setConfig(data);setProvider(data.settings?.provider_id??data.providers[0]?.id??'');setEnabled(data.settings?.enabled??false);setDays(data.settings?.cache_days??30);}).catch(e=>{if(alive&&current===generation)setError(e.message);});};load();window.addEventListener(STORE_CONTEXT_CHANGED_EVENT,load);return()=>{alive=false;window.removeEventListener(STORE_CONTEXT_CHANGED_EVENT,load);};},[]);
 async function save(){const storeId=getActiveStoreId();setBusy(true);setError('');setMessage('');try{await nestRequest('/device-reference/settings',{method:'PUT',body:JSON.stringify({providerId:provider,enabled,cacheDays:days,...(key?{apiKey:key}:{})})});if(getActiveStoreId()!==storeId)return;setKey('');const data=await nestRequest<Config>('/device-reference/settings');if(getActiveStoreId()!==storeId)return;setConfig(data);setMessage('Configuração salva para esta loja.');}catch(e){if(getActiveStoreId()===storeId)setError((e as Error).message);}finally{if(getActiveStoreId()===storeId)setBusy(false);}}
 return <section className="admin-page"><h2>Configuração da consulta</h2><p>Especificações, cores e capacidades são consultadas no fornecedor e registradas no banco desta loja. Custos e preços de venda são definidos no cadastro do produto.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<article className="admin-card"><div className="admin-form"><AdminPicker label="Fornecedor de especificações" value={provider} disabled={busy||!config} options={(config?.providers??[]).map(p=>({value:p.id,label:p.name}))} onChange={setProvider}/><label>Chave de acesso<input type="password" autoComplete="new-password" value={key} disabled={busy||!config} placeholder={config?.settings?.configured?'Chave cadastrada; deixe em branco para manter':'Informe a chave do fornecedor'} onChange={e=>setKey(e.target.value)}/></label><label>Atualizar dados após (dias)<input type="number" min={1} max={365} value={days} disabled={busy||!config} onChange={e=>setDays(Number(e.target.value))}/></label><label className="admin-checkbox"><input type="checkbox" checked={enabled} disabled={busy||!config} onChange={e=>setEnabled(e.target.checked)}/>Ativar consulta automática nesta loja</label></div><p>{config?.providers.find(p=>p.id===provider)&&<><a href={config.providers.find(p=>p.id===provider)!.docs_url} target="_blank" rel="noreferrer">Documentação da API</a></>}</p><p>Marcas reconhecidas: {(config?.brands??[]).map(b=>b.name).join(', ')}</p><div className="settings-form-actions"><button type="button" className="btn btn--primary" disabled={busy||!config||!provider} onClick={()=>void save()}>{busy?'Salvando…':'Salvar configuração'}</button></div></article></section>;
}
