import {Router} from 'express';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {PoolClient} from 'pg';
import {pool} from '../db/pool.js';
import {requireAuth} from '../middlewares/authMiddleware.js';
import {unreservedQuantity} from '../services/commercialReservations.js';
export const stockInvoicesRouter=Router();
stockInvoicesRouter.use('/api/v1/stock-invoices',requireAuth);
const headerSchema=z.object({kind:z.enum(['entry','exit']),number:z.string().trim().max(80).default(''),series:z.string().max(20).default(''),supplierId:z.string().default(''),issuedAt:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),movementAt:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),notes:z.string().default(''),documentPurpose:z.string().default('normal'),customerName:z.string().default(''),customerDocument:z.string().default(''),cfopCode:z.string().default(''),targetStoreId:z.string().default(''),refNfeKey:z.string().default(''),natOp:z.string().default(''),modFrete:z.string().default('9'),vFrete:z.number().nonnegative().default(0),vDesc:z.number().nonnegative().default(0),vOutro:z.number().nonnegative().default(0),infCpl:z.string().default('')});
const error=(message:string,status=400)=>Object.assign(new Error(message),{status});
async function loadInvoice(db:Pick<PoolClient,'query'>,store:string,id:string,lock=false){
 const row=(await db.query('SELECT * FROM stock_invoices WHERE id=$1 AND store_id=$2'+(lock?' FOR UPDATE':''),[id,store])).rows[0];if(!row)throw error('Nota não encontrada nesta loja.',404);return row;
}
async function formatInvoice(db:Pick<PoolClient,'query'>,row:any){
 const lines=(await db.query('SELECT l.*,s.name FROM stock_invoice_lines l JOIN stock_items s ON s.id=l.stock_item_id AND s.store_id=$2 WHERE l.invoice_id=$1 ORDER BY l.id',[row.id,row.store_id])).rows;
 return {...row.details,id:row.id,kind:row.kind,status:row.status,number:row.number,series:row.series,supplierId:row.supplier_id??'',issuedAt:row.issue_date?String(row.issue_date instanceof Date?row.issue_date.toISOString():row.issue_date).slice(0,10):'',notes:row.notes,createdAt:row.created_at,updatedAt:row.updated_at,postedAt:row.posted_at,lines:lines.map(l=>({id:l.id,stockId:l.stock_item_id,name:l.name,qty:Number(l.qty),unitCost:Number(l.unit_cost),unitPrice:Number(l.unit_price)}))};
}
async function validateSupplier(db:Pick<PoolClient,'query'>,store:string,id?:string){if(id&&!(await db.query('SELECT id FROM suppliers WHERE id=$1 AND store_id=$2',[id,store])).rows.length)throw error('Fornecedor não pertence à loja.');}
stockInvoicesRouter.get('/api/v1/stock-invoices',async(req,res,next)=>{try{const rows=(await pool.query('SELECT * FROM stock_invoices WHERE store_id=$1 AND ($2::text IS NULL OR kind=$2) AND ($3::text IS NULL OR status=$3) ORDER BY created_at DESC',[req.storeId,req.query.kind??null,req.query.status??null])).rows;const result=[];for(const row of rows)result.push(await formatInvoice(pool,row));res.json({success:true,data:result});}catch(e){next(e);}});
stockInvoicesRouter.get('/api/v1/stock-invoices/:id',async(req,res,next)=>{try{res.json({success:true,data:await formatInvoice(pool,await loadInvoice(pool,req.storeId!,req.params.id))});}catch(e){next(e);}});
stockInvoicesRouter.post('/api/v1/stock-invoices',async(req,res,next)=>{try{const b=headerSchema.parse(req.body);await validateSupplier(pool,req.storeId!,b.supplierId);if(b.targetStoreId)throw error('Transferências devem ser registradas pelo fluxo de transferência de estoque.');const id=randomUUID();const row=(await pool.query('INSERT INTO stock_invoices(id,store_id,supplier_id,number,series,issue_date,notes,kind,details) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[id,req.storeId,b.supplierId||null,b.number,b.series,b.issuedAt??null,b.notes,b.kind,JSON.stringify(b)])).rows[0];res.status(201).json({success:true,data:await formatInvoice(pool,row)});}catch(e){next(e);}});
stockInvoicesRouter.patch('/api/v1/stock-invoices/:id',async(req,res,next)=>{const db=await pool.connect();try{await db.query('BEGIN');const curr=await loadInvoice(db,req.storeId!,req.params.id,true);if(curr.status!=='draft')throw error('Somente rascunhos podem ser alterados.',409);const patch=headerSchema.omit({kind:true}).partial().parse(req.body);const b={...curr.details,...patch};await validateSupplier(db,req.storeId!,b.supplierId);if(b.targetStoreId)throw error('Use o fluxo de transferência de estoque.');const row=(await db.query('UPDATE stock_invoices SET supplier_id=$3,number=$4,series=$5,issue_date=$6,notes=$7,details=$8,updated_at=now() WHERE id=$1 AND store_id=$2 RETURNING *',[curr.id,req.storeId,b.supplierId||null,b.number??curr.number,b.series??curr.series,b.issuedAt||curr.issue_date,b.notes??curr.notes,JSON.stringify(b)])).rows[0];await db.query('COMMIT');res.json({success:true,data:await formatInvoice(pool,row)});}catch(e){await db.query('ROLLBACK');next(e);}finally{db.release();}});
stockInvoicesRouter.post('/api/v1/stock-invoices/:id/lines',async(req,res,next)=>{const db=await pool.connect();try{const b=z.object({stockId:z.string(),qty:z.number().int().positive(),unitCost:z.number().finite().nonnegative().optional(),unitPrice:z.number().finite().nonnegative().optional()}).parse(req.body);await db.query('BEGIN');const row=await loadInvoice(db,req.storeId!,req.params.id,true);if(row.status!=='draft')throw error('Nota já processada.',409);const stock=(await db.query('SELECT * FROM stock_items WHERE id=$1 AND store_id=$2 AND active=true',[b.stockId,req.storeId])).rows[0];if(!stock)throw error('Produto não pertence à loja.');await db.query('INSERT INTO stock_invoice_lines(id,invoice_id,stock_item_id,qty,unit_cost,total_cost,unit_price) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),row.id,stock.id,b.qty,b.unitCost??Number(stock.cost),b.qty*(b.unitCost??Number(stock.cost)),b.unitPrice??Number(stock.price)]);await db.query('COMMIT');res.status(201).json({success:true,data:await formatInvoice(pool,row)});}catch(e){await db.query('ROLLBACK');next(e);}finally{db.release();}});
stockInvoicesRouter.delete('/api/v1/stock-invoices/:id/lines/:lineId',async(req,res,next)=>{const db=await pool.connect();try{await db.query('BEGIN');const row=await loadInvoice(db,req.storeId!,req.params.id,true);if(row.status!=='draft')throw error('Nota já processada.',409);await db.query('DELETE FROM stock_invoice_lines WHERE id=$1 AND invoice_id=$2',[req.params.lineId,row.id]);await db.query('COMMIT');res.json({success:true,data:await formatInvoice(pool,row)});}catch(e){await db.query('ROLLBACK');next(e);}finally{db.release();}});
for(const action of ['post','cancel'] as const)stockInvoicesRouter.post('/api/v1/stock-invoices/:id/'+action,async(req,res,next)=>{const db=await pool.connect();try{
 await db.query('BEGIN');const row=await loadInvoice(db,req.storeId!,req.params.id,true);
 if(action==='post'&&row.status==='posted'||action==='cancel'&&row.status==='cancelled'){await db.query('COMMIT');res.json({success:true,data:await formatInvoice(pool,row)});return;}
 if(action==='post'&&row.status!=='draft')throw error('Nota cancelada.',409);
 const lines=(await db.query('SELECT * FROM stock_invoice_lines WHERE invoice_id=$1 ORDER BY stock_item_id,id',[row.id])).rows;
 if(action==='post'&&!lines.length)throw error('Inclua ao menos um item.');
 if(action==='post'&&(!row.number.trim()||!row.issue_date))throw error('Informe número e data de emissão da nota.');
 if(action==='post'&&row.kind==='entry'&&!row.supplier_id)throw error('Informe o fornecedor da entrada.');
 const move=action==='post'||row.status==='posted';
 if(move)for(const line of lines){
  const stock=(await db.query('SELECT * FROM stock_items WHERE id=$1 AND store_id=$2 FOR UPDATE',[line.stock_item_id,req.storeId])).rows[0];if(!stock||!stock.active)throw error('Produto indisponível nesta loja.');
  const direction=(row.kind==='entry'?1:-1)*(action==='cancel'?-1:1);const qty=Number(line.qty);const prev=Number(stock.qty);const nextQty=prev+direction*qty;
  if(direction<0&&await unreservedQuantity(db,req.storeId!,stock.id,prev)<qty)throw error('Saldo insuficiente ou reservado para movimentar a nota.',409);
  let avg=Number(stock.avg_cost);let cost=Number(stock.cost);
  if(row.kind==='entry'&&action==='post'){cost=Number(line.unit_cost);avg=nextQty>0?Math.round((prev*avg+qty*cost)/nextQty*100)/100:cost;}
  if(row.kind==='entry'&&action==='cancel'){const remainder=prev*avg-qty*Number(line.unit_cost);if(remainder<-0.01)throw error('O custo do estoque mudou após a entrada. Registre a devolução pelo fluxo apropriado.',409);avg=nextQty>0?Math.round(Math.max(0,remainder)/nextQty*100)/100:0;const last=(await db.query("SELECT m.unit_cost FROM stock_movements m LEFT JOIN stock_invoices i ON i.id=m.ref_id AND i.store_id=m.store_id WHERE m.stock_id=$1 AND m.store_id=$2 AND m.type='in' AND m.ref_id IS DISTINCT FROM $3 AND (i.id IS NULL OR i.status<>'cancelled') AND m.ref_type<>'invoice_reversal' ORDER BY m.created_at DESC,m.id DESC LIMIT 1",[stock.id,req.storeId,row.id])).rows[0];cost=Number(last?.unit_cost??0);}
  await db.query('UPDATE stock_items SET qty=$3,avg_cost=$4,cost=$5,updated_at=now() WHERE id=$1 AND store_id=$2',[stock.id,req.storeId,nextQty,avg,cost]);
  await db.query('INSERT INTO stock_movements(id,store_id,stock_id,type,qty,previous_qty,new_qty,unit_cost,ref_type,ref_id,operator_name,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[randomUUID(),req.storeId,stock.id,direction>0?'in':'out',qty,prev,nextQty,Number(line.unit_cost),action==='post'?'invoice':'invoice_reversal',row.id,req.user!.name,'Nota '+row.number]);
 }
 const changed=(await db.query("UPDATE stock_invoices SET status=$3,posted_at=CASE WHEN $3='posted' THEN now() ELSE posted_at END,total_amount=$4,updated_at=now() WHERE id=$1 AND store_id=$2 RETURNING *",[row.id,req.storeId,action==='post'?'posted':'cancelled',Math.max(0,lines.reduce((sum,l)=>sum+Number(l.qty)*Number(row.kind==='entry'?l.unit_cost:l.unit_price),0)+Number(row.details.vFrete??0)+Number(row.details.vOutro??0)-Number(row.details.vDesc??0))])).rows[0];
 await db.query('COMMIT');res.json({success:true,data:await formatInvoice(pool,changed)});
 }catch(e){await db.query('ROLLBACK');next(e);}finally{db.release();}});
