ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_phone TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_address TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS panel_theme TEXT NOT NULL DEFAULT 'light';
