-- Preserve the existing customer-approved Cell Ponto rate table only for its store.
INSERT INTO store_module_state(store_id,module_key,data,revision,updated_by)
SELECT id,'card-rates','[{"id":"MACH-DEFAULT-01","name":"Maquininha Principal (Loja)","model":"Smart POS","isDefaultTotem":true,"defaultBrandId":"master","brands":[{"id":"master","name":"Mastercard","debitRate":1.39,"installments":[{"installment":1,"rate":3.14},{"installment":2,"rate":5.28},{"installment":3,"rate":6.45},{"installment":4,"rate":7.6},{"installment":5,"rate":8.75},{"installment":6,"rate":9.9},{"installment":7,"rate":11.05},{"installment":8,"rate":12.2},{"installment":9,"rate":13.35},{"installment":10,"rate":14.5},{"installment":11,"rate":15.65},{"installment":12,"rate":16.8}],"active":true},{"id":"visa","name":"Visa","debitRate":1.39,"installments":[{"installment":1,"rate":3.14},{"installment":2,"rate":5.28},{"installment":3,"rate":6.45},{"installment":4,"rate":7.6},{"installment":5,"rate":8.75},{"installment":6,"rate":9.9},{"installment":7,"rate":11.05},{"installment":8,"rate":12.2},{"installment":9,"rate":13.35},{"installment":10,"rate":14.5},{"installment":11,"rate":15.65},{"installment":12,"rate":16.8}],"active":true},{"id":"elo","name":"Elo","debitRate":1.85,"installments":[{"installment":1,"rate":3.8},{"installment":2,"rate":5.95},{"installment":3,"rate":7.1},{"installment":4,"rate":8.25},{"installment":5,"rate":9.4},{"installment":6,"rate":10.55},{"installment":7,"rate":11.7},{"installment":8,"rate":12.85},{"installment":9,"rate":14},{"installment":10,"rate":15.15},{"installment":11,"rate":16.3},{"installment":12,"rate":17.45}],"active":true},{"id":"hipercard","name":"Hipercard","debitRate":1.99,"installments":[{"installment":1,"rate":3.99},{"installment":2,"rate":6.15},{"installment":3,"rate":7.3},{"installment":4,"rate":8.45},{"installment":5,"rate":9.6},{"installment":6,"rate":10.75},{"installment":7,"rate":11.9},{"installment":8,"rate":13.05},{"installment":9,"rate":14.2},{"installment":10,"rate":15.35},{"installment":11,"rate":16.5},{"installment":12,"rate":17.65}],"active":true},{"id":"amex","name":"American Express","debitRate":2.2,"installments":[{"installment":1,"rate":4.2},{"installment":2,"rate":6.4},{"installment":3,"rate":7.55},{"installment":4,"rate":8.7},{"installment":5,"rate":9.85},{"installment":6,"rate":11},{"installment":7,"rate":12.15},{"installment":8,"rate":13.3},{"installment":9,"rate":14.45},{"installment":10,"rate":15.6},{"installment":11,"rate":16.75},{"installment":12,"rate":17.9}],"active":true}],"active":true,"createdAt":"2026-01-01T00:00:00.000Z","updatedAt":"2026-10-04T14:35:43.752Z"}]'::jsonb,1,(SELECT u.id FROM users u JOIN user_stores us ON us.user_id=u.id WHERE us.store_id=stores.id AND u.active=true AND us.role='admin' ORDER BY u.created_at,u.id LIMIT 1) FROM stores WHERE id='STR-PRT-MUM5YWBG8DSR'
ON CONFLICT(store_id,module_key) DO NOTHING;
UPDATE commercial_store_customization SET settings=jsonb_set(settings,'{showCardRates}','true'::jsonb),updated_at=now() WHERE store_id='STR-PRT-MUM5YWBG8DSR';

INSERT INTO commercial_store_customization(store_id,settings)
SELECT id,jsonb_build_object('segmentId',COALESCE(segment,'assistencia_tecnica'),'segmentName','Configuração da loja',
 'showCardRates',true,'showImei',true,'showDevicePassword',true,'showTablesAndKitchen',false,'showCardapioDigital',false,
 'showTechnicalBench',true,'showSizeColorGrid',false)
FROM stores WHERE id='STR-PRT-MUM5YWBG8DSR'
ON CONFLICT(store_id) DO UPDATE SET settings=COALESCE(commercial_store_customization.settings,'{}'::jsonb)||'{"showCardRates":true}'::jsonb,updated_at=now();
